baseURL = "https://lennarthenke.github.io/"
languageCode = "en-us"
title = "Lennart Henke"
enableRobotsTXT = true
enableInlineShortcodes = true
enableEmoji = true

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 5 # articles per page

[params]
	subtitle = "A computer science and software blog."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Main menu Items
[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Posts"
	url = "/posts"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 3

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 4

# Footer
[[params.social]]
	name = "Github"
	icon = "github"
	url = "https://github.com/lennarthenke"

[[params.social]]
	name = "Twitter"
	icon = "twitter"
	url = "https://twitter.com/lennarthenke"

[[params.social]]
	name = "RSS"
	icon = "rss"
	url = "/index.xml"